### ISSUE TITLE
USE FUNCTIONS

### ISSUE THREAD

**Issue by dineshkumar227** [chin123/gpa#2]
F  U  N  C  T  I  O  N  S
U
N
C
T
 I
O
N
S

**Comment by chin123** [comment]
Hi Dinesh Kumar,  
Thank you for your issue! Here at chin123, we take feedback very seriously. We will be sure to take your opinions into account in the future!  

Stay safe and best regards,
All of us at [chin123](https://github.com/chin123)

**Comment by dineshkumar227** [comment]
Done
