### ISSUE TITLE
500 Error when accessing course pages from search results if the course title contains parentheses

### ISSUE THREAD

**Issue by 94rain** [chin123/gpa#8]
When I click the url of `ARTD 209: Chado (The Way of Tea)` from [serach results](https://chinmayamahesh.me/gpa?course=ARTD+20&semester=All), it returns [500 error](https://chinmayamahesh.me/gpa?course=ARTD%20209%3A%20Chado%20%28The%20Way%20of%20Tea%29&semester=All&exact=true).
However, it is OK to access https://chinmayamahesh.me/gpa?course=ARTD+209&semester=All

Some other courses with parentheses in titles also have this problem:
[search result of CHLH 199](https://chinmayamahesh.me/gpa?course=CHLH+199&semester=All), [course page](https://chinmayamahesh.me/gpa?course=CHLH%20199%3A%20Campus%20Acq%20Rape%20Educ%20%28CARE%29&semester=All&exact=true); [search result of LAW 501](https://chinmayamahesh.me/gpa?course=LAW+501&semester=All), etc...

**Comment by chin123** [comment]
(finally) fixed, thanks!
